all:
#svnet-y := main.o pdp.o
cp ../../../../samsung_modemctl/svnet/main.o ./main.o 	+= main.o
cp ../../../../samsung_modemctl/svnet/pdp.o ./pdp.o 	+= pdp.o
#svnet-y += sipc4.o
cp ../../../../samsung_modemctl/svnet/sipc4.o ./sipc4.o	+= sipc4.o
#obj-y	+= svnet.o
cp ../../../../samsung_modemctl/svnet/svnet.o ./svnet.o	+= svnet.o
