obj-$(CONFIG_PHONE_ARIES)	+= modemctl/
obj-$(CONFIG_PHONE_ARIES)	+= onedram/
obj-$(CONFIG_PHONE_ARIES)	+= svnet/
obj-$(CONFIG_PHONE_ARIES_CDMA)	+= dpram/
#obj-$(CONFIG_PHONE_CRESPO)	+= modem_ctl.o modem_io.o modem_dbg.o
#ifdef CONFIG_PHONE_ARIES
all:
cp -R ../../../stable/samsung_modemctl/* ./ 	+= built_in.o
#endif
